import java.io.File;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FamilyTree {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new FamilyTree().getGreeting());

        FamilyTree tree = new FamilyTree();

        File file = new File("input_hard.txt");

        try {
            Scanner in = new Scanner(file);

            // nodes in tree
            final int size = in.nextInt();
            // n-1
            for (int i = 0; i < size - 1; i++) {
                int parent = in.nextInt();
                int child = in.nextInt();
                //tree.addNode(parent, child);
            }

            final int queries = in.nextInt();
            for (int i = 0; i < queries; i++) {
                if (in.next().contains("add")) {
                    int id = in.nextInt();
                    int value = in.nextInt();
                    //tree.addValue(id, value);
                } else {
                    int id = in.nextInt();
                    int id2 = in.nextInt();
                    //tree.maxValue(id, id2);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
